/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dicom;

import dicom.basedatos.DBconecction;
import dicom.config.DCMconfig;
import dicom.operations.DCMcfind;
import dicom.utils.Study;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author MH
 */
public class DCMmainWindow extends javax.swing.JFrame {

    /**
     * Creates new form DCMmainWindow
     */
    public DCMmainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDCMfind = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studyPanel = new javax.swing.JScrollPane();
        patientList = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDCMfind.setText("Verificar");
        btnDCMfind.setActionCommand("dcmFind");
        btnDCMfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDCMfindActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        studyPanel.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Estudios inconcistentes"));
        studyPanel.setViewportView(patientList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDCMfind)
                    .addComponent(jButton2))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnDCMfind)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studyPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDCMfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDCMfindActionPerformed
        // TODO add your handling code here:
        
         DCMconfig dcmConfig= new DCMconfig();
         dcmConfig.setDateStart(new Date(System.currentTimeMillis()));
        dcmConfig.setFormat("yyyyMMdd");
       // System.out.println(dcmConfig.getDateStart());
       // dcmConfig.setLOCAL_AE("MHPC");
       // dcmConfig.setREMOTE_AE("SERVERPACS");
        dcmConfig.setREMOTE_HOST("10.16.107.13");
        dcmConfig.setLOCAL_AE("EMULATOR_TEST");
        dcmConfig.setREMOTE_AE("phia-pacsFIR");
       
        dcmConfig.setREMOTE_PORT(2104);
                
    /*    // TODO code application logic here
        //DCMinfo dcmInfo = new DCMinfo();
       
       
       // dcmInfo.readDicomAttributes ();
      // DCMcecho dcmcEcho= new DCMcecho(dcmConfig);
      //  dcmcEcho.echo();
       
       
        //DCMassociation dcmAssociation = new DCMassociation(dcmConfig);
        //dcmAssociation.DCMstartAssociation();
        
        
        //DCMimage dcmImage = new DCMimage();
        //dcmImage.image();
        
       
        
        //DCMwado dcmWado = new DCMwado(dcmConfig);
       // dcmWado.wadoRequest();
        
      
      // Empieza con HGDL y no esta en la WL
     */
      
    new Thread() {
             @Override
             public void run() {
                 DCMcfind cFind= new DCMcfind(dcmConfig);
                TreeMap<String,Study>   pacsPatients =  cFind.cFind();
                TreeMap <String,Study>  pacsPatients2 = (TreeMap) pacsPatients.clone();
                 DBconecction dbConnection = new DBconecction(dcmConfig);
                TreeMap   wlPatients = dbConnection.connectionTest();
       
      
      Set <String> anKeys = pacsPatients2.keySet();
      anKeys.forEach(
              key -> {
                  if ( (key.startsWith("HGDL") && !wlPatients.containsKey(key) ))
                  {
                     pacsPatients.remove(key);
                  }
              }
      
      );
      
        System.out.println("Estudios con inconsistencias: " + pacsPatients.size());
                 
                 
                 
                  
                 ArrayList<String> sts = new ArrayList<String>();
                
                
                 pacsPatients.forEach( (an,st) ->{
                        sts.add(st.getStudyPatient().getPatientName());
                        patientList.add(st.getStudyPatient().getPatientName() );
                 });
                 
                    
                    studyPanel.setVisible(true);
                    
       
       int i=0;
             }
    }.start();
    
        
    }//GEN-LAST:event_btnDCMfindActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDCMfind;
    private javax.swing.JButton jButton2;
    private java.awt.List patientList;
    private javax.swing.JScrollPane studyPanel;
    // End of variables declaration//GEN-END:variables
}
