/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dicom;

import dicom.basedatos.DBconecction;
import dicom.config.DCMconfig;
import dicom.operations.DCMcfind;
import java.util.Date;
import java.util.Set;
import java.util.TreeMap;

/**
 *
 * @author MH
 */
public class DCMmainWindow extends javax.swing.JFrame {

    /**
     * Creates new form DCMmainWindow
     */
    public DCMmainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnDCMfind = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnDCMfind.setText("Verificar");
        btnDCMfind.setActionCommand("dcmFind");
        btnDCMfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDCMfindActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDCMfind)
                    .addComponent(jButton2))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnDCMfind)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDCMfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDCMfindActionPerformed
        // TODO add your handling code here:
        
         DCMconfig dcmConfig= new DCMconfig();
         dcmConfig.setDateStart(new Date(System.currentTimeMillis()));
        dcmConfig.setFormat("yyyyMMdd");
       // System.out.println(dcmConfig.getDateStart());
       // dcmConfig.setLOCAL_AE("MHPC");
       // dcmConfig.setREMOTE_AE("SERVERPACS");
        dcmConfig.setREMOTE_HOST("10.16.107.13");
        dcmConfig.setLOCAL_AE("EMULATOR_TEST");
        dcmConfig.setREMOTE_AE("phia-pacsFIR");
       
        dcmConfig.setREMOTE_PORT(2104);
                
    /*    // TODO code application logic here
        //DCMinfo dcmInfo = new DCMinfo();
       
       
       // dcmInfo.readDicomAttributes ();
      // DCMcecho dcmcEcho= new DCMcecho(dcmConfig);
      //  dcmcEcho.echo();
       
       
        //DCMassociation dcmAssociation = new DCMassociation(dcmConfig);
        //dcmAssociation.DCMstartAssociation();
        
        
        //DCMimage dcmImage = new DCMimage();
        //dcmImage.image();
        
       
        
        //DCMwado dcmWado = new DCMwado(dcmConfig);
       // dcmWado.wadoRequest();
        
      
      // Empieza con HGDL y no esta en la WL
     */
      
    new Thread() {
             @Override
             public void run() {
                 DCMcfind cFind= new DCMcfind(dcmConfig);
      TreeMap   pacsPatients =  cFind.cFind();
      TreeMap   pacsPatients2 = (TreeMap) pacsPatients.clone();
       DBconecction dbConnection = new DBconecction(dcmConfig);
      TreeMap   wlPatients = dbConnection.connectionTest();
       
      
      Set <String> anKeys = pacsPatients2.keySet();
      anKeys.forEach(
              key -> {
                  if ( (key.startsWith("HGDL") && !wlPatients.containsKey(key) ))
                  {
                     pacsPatients.remove(key);
                  }
              }
      
      );
      
        System.out.println("Estudios con inconsistencias: " + pacsPatients.size());
        
        
       
       int i=0;
             }
    }.start();
    
        
    }//GEN-LAST:event_btnDCMfindActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDCMfind;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
